# Generated by Django 6.0.7 on 2026-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_cinema_movie_backdrop_url_movie_display_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
